"""
question_bank.py
Structured interview question bank.
Each record: question, role, round, topic, difficulty, importance, type
"""

QUESTIONS = [
    # ── APTITUDE ──────────────────────────────────────────────────────────────
    {
        "question": "A train 150 m long is running at a speed of 60 km/h. In what time will it pass a man standing at a station?",
        "role": "General Placement",
        "round": "Aptitude",
        "topic": "Aptitude",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Aptitude",
    },
    {
        "question": "A can do a work in 12 days and B can do the same work in 18 days. In how many days can they complete the work together?",
        "role": "General Placement",
        "round": "Aptitude",
        "topic": "Aptitude",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Aptitude",
    },
    {
        "question": "If 6 men can do a piece of work in 10 days, how many men are needed to complete the work in 4 days?",
        "role": "General Placement",
        "round": "Aptitude",
        "topic": "Aptitude",
        "difficulty": "Medium",
        "importance": "Medium",
        "type": "Aptitude",
    },
    {
        "question": "Find the next number in the series: 2, 6, 12, 20, 30, ?",
        "role": "General Placement",
        "round": "Aptitude",
        "topic": "Aptitude",
        "difficulty": "Medium",
        "importance": "Medium",
        "type": "Aptitude",
    },
    {
        "question": "What is the probability of getting a sum of 7 when two dice are rolled?",
        "role": "General Placement",
        "round": "Aptitude",
        "topic": "Aptitude",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Aptitude",
    },

    # ── EMBEDDED C / C++ ──────────────────────────────────────────────────────
    {
        "question": "What is the difference between a pointer and a reference in C++?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Explain the use of the 'volatile' keyword in C. Give an embedded systems example.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is a dangling pointer? How do you prevent it?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Explain static, extern, and register storage classes in C.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Medium",
        "importance": "Medium",
        "type": "Technical",
    },
    {
        "question": "What is the difference between malloc() and calloc()? When would you use each?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "How does a struct differ from a union in C? Give an embedded use case for a union.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What are bit fields in C? Write an example defining a 4-bit and a 2-bit field in a struct.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Explain function pointers in C and give one practical use in embedded firmware.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Hard",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is endianness? How would you check whether a system is little-endian or big-endian using C code?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },

    # ── DIGITAL ELECTRONICS ───────────────────────────────────────────────────
    {
        "question": "What is a flip-flop? Explain the difference between SR, D, JK, and T flip-flops.",
        "role": "Electronics Engineer",
        "round": "Technical",
        "topic": "Digital Electronics",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is the difference between combinational and sequential circuits? Give two examples of each.",
        "role": "Electronics Engineer",
        "round": "Technical",
        "topic": "Digital Electronics",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Simplify the Boolean expression F = AB' + A'B + AB using a Karnaugh map.",
        "role": "Electronics Engineer",
        "round": "Technical",
        "topic": "Digital Electronics",
        "difficulty": "Medium",
        "importance": "Medium",
        "type": "Technical",
    },
    {
        "question": "What is a multiplexer? Design a 4-to-1 MUX using logic gates.",
        "role": "Electronics Engineer",
        "round": "Technical",
        "topic": "Digital Electronics",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Explain the difference between synchronous and asynchronous counters.",
        "role": "Electronics Engineer",
        "round": "Technical",
        "topic": "Digital Electronics",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is a tri-state buffer? Where is it used in digital systems?",
        "role": "Electronics Engineer",
        "round": "Technical",
        "topic": "Digital Electronics",
        "difficulty": "Easy",
        "importance": "Medium",
        "type": "Technical",
    },

    # ── MICROCONTROLLERS ──────────────────────────────────────────────────────
    {
        "question": "What is the difference between a microprocessor and a microcontroller? Give examples of each.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Microcontrollers",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Explain the difference between polling and interrupt-driven I/O. Which is preferred in embedded systems and why?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Microcontrollers",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is PWM? How is it generated in a microcontroller and what are its applications?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Microcontrollers",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Explain how an ADC works in a microcontroller. What parameters affect its resolution?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Microcontrollers",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What are timers in a microcontroller? Explain timer overflow and how to configure a timer for a specific time period.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Microcontrollers",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is the stack pointer in a microcontroller? What happens to it during an interrupt service routine?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Microcontrollers",
        "difficulty": "Hard",
        "importance": "Medium",
        "type": "Technical",
    },
    {
        "question": "Explain the difference between RISC and CISC architecture. Which does the ARM Cortex-M series follow?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Microcontrollers",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },

    # ── COMMUNICATION PROTOCOLS ───────────────────────────────────────────────
    {
        "question": "Explain the difference between UART and SPI in terms of wires, speed, full-duplex capability, and use cases.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Communication Protocols",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "How does I2C communication work? Explain the role of SDA, SCL, addressing, and ACK/NACK.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Communication Protocols",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is CAN protocol? Why is it used in automotive and industrial applications?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Communication Protocols",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Compare SPI and I2C: which would you choose for a sensor interface requiring high speed, and why?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Communication Protocols",
        "difficulty": "Hard",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is baud rate in UART? What happens if the baud rates of the transmitter and receiver do not match?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Communication Protocols",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Technical",
    },

    # ── DEBUGGING ─────────────────────────────────────────────────────────────
    {
        "question": "Describe your approach to debugging an embedded firmware issue where the system hangs intermittently.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Debugging",
        "difficulty": "Hard",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is a watchdog timer? How does it help in embedded fault detection?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Debugging",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Explain how you would use an oscilloscope or logic analyzer to debug a serial communication issue on SPI.",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Debugging",
        "difficulty": "Hard",
        "importance": "Medium",
        "type": "Technical",
    },
    {
        "question": "What is a stack overflow in an embedded system? How would you detect and fix it?",
        "role": "Embedded Engineer",
        "round": "Technical",
        "topic": "Debugging",
        "difficulty": "Hard",
        "importance": "High",
        "type": "Technical",
    },

    # ── PROJECT ───────────────────────────────────────────────────────────────
    {
        "question": "Explain your final year or main project: what problem does it solve, how did you design it, and what was your individual contribution?",
        "role": "General Placement",
        "round": "Technical",
        "topic": "Project",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Project",
    },
    {
        "question": "What challenges did you face during your project and how did you overcome them?",
        "role": "General Placement",
        "round": "Technical",
        "topic": "Project",
        "difficulty": "Medium",
        "importance": "High",
        "type": "Project",
    },
    {
        "question": "If you were to improve your project further, what features would you add and why?",
        "role": "General Placement",
        "round": "Technical",
        "topic": "Project",
        "difficulty": "Easy",
        "importance": "Medium",
        "type": "Project",
    },
    {
        "question": "What technologies and tools did you use in your project? Why did you choose them over alternatives?",
        "role": "General Placement",
        "round": "Technical",
        "topic": "Project",
        "difficulty": "Easy",
        "importance": "Medium",
        "type": "Project",
    },

    # ── BEHAVIORAL / HR ───────────────────────────────────────────────────────
    {
        "question": "Tell me about yourself.",
        "role": "General Placement",
        "round": "HR",
        "topic": "Behavioral / HR",
        "difficulty": "Easy",
        "importance": "High",
        "type": "HR",
    },
    {
        "question": "What are your strengths and weaknesses?",
        "role": "General Placement",
        "round": "HR",
        "topic": "Behavioral / HR",
        "difficulty": "Easy",
        "importance": "High",
        "type": "HR",
    },
    {
        "question": "Describe a situation where you worked in a team to solve a difficult problem. What was your role?",
        "role": "General Placement",
        "round": "HR",
        "topic": "Behavioral / HR",
        "difficulty": "Medium",
        "importance": "High",
        "type": "HR",
    },
    {
        "question": "Where do you see yourself in five years?",
        "role": "General Placement",
        "round": "HR",
        "topic": "Behavioral / HR",
        "difficulty": "Easy",
        "importance": "High",
        "type": "HR",
    },
    {
        "question": "Describe a time when you had a conflict with a teammate. How did you handle it?",
        "role": "General Placement",
        "round": "HR",
        "topic": "Behavioral / HR",
        "difficulty": "Medium",
        "importance": "Medium",
        "type": "HR",
    },
    {
        "question": "Why do you want to work for this company?",
        "role": "General Placement",
        "round": "HR",
        "topic": "Behavioral / HR",
        "difficulty": "Easy",
        "importance": "High",
        "type": "HR",
    },
    {
        "question": "Tell me about a time you failed. What did you learn from it?",
        "role": "General Placement",
        "round": "HR",
        "topic": "Behavioral / HR",
        "difficulty": "Medium",
        "importance": "High",
        "type": "HR",
    },

    # ── SOFTWARE ENGINEER SPECIFIC ────────────────────────────────────────────
    {
        "question": "Explain the difference between a stack and a queue. Give one real-world use case for each.",
        "role": "Software Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "What is the time complexity of binary search? Explain with an example.",
        "role": "Software Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Technical",
    },
    {
        "question": "Explain object-oriented programming concepts: encapsulation, inheritance, polymorphism, and abstraction.",
        "role": "Software Engineer",
        "round": "Technical",
        "topic": "Embedded C / C++",
        "difficulty": "Easy",
        "importance": "High",
        "type": "Technical",
    },
]


def get_all_questions():
    return QUESTIONS


def get_roles():
    return sorted(set(q["role"] for q in QUESTIONS))


def get_topics():
    return sorted(set(q["topic"] for q in QUESTIONS))


def get_rounds():
    return sorted(set(q["round"] for q in QUESTIONS))


def get_difficulties():
    return ["Easy", "Medium", "Hard"]
